# Generated by Django 5.2.6 on 2025-09-24 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lease_servicechargepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.house'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
