# Generated by Django 5.2.6 on 2025-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_lease_house_alter_lease_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance_docs/')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_images/'),
        ),
    ]
