# Generated by Django 5.2.6 on 2025-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_generalmaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_images/'),
        ),
    ]
