# Generated by Django 5.2.6 on 2025-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_maintenancerequest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='image',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_images/'),
        ),
    ]
